#version 450

//#define FURNITURE
#define BOX

struct Triangle {
    vec4 v0;
    vec4 v1;
    vec4 v2;
    vec4 normal;
};

struct BVHNode {
    vec3 aabbMin;
    int leftChild;
    vec3 aabbMax;
    int rightChild;
    int triangleStart;
    int triangleCount;
};

struct Ray {
    vec3 origin;
    vec3 dir;
};

struct HitInfo {
    float t;
    vec3 normal;
    vec3 color;
    bool isLight;
};

struct Quad {

    vec3 minP;
    vec3 maxP;
    vec3 normal;
    vec3 color;
    bool isLight;

}; 

layout(local_size_x = 8, local_size_y = 8) in;


layout(rgba32f, set = 0, binding = 0) uniform image2D outImage;

layout(push_constant) uniform PushConstants {
    uint  frameCount;
    uint  useNEE;
    uint  useRealLens;
    float focalLength;
    float apertureSize;
} pc;


layout(binding = 1) readonly buffer TriangleBuffer {

    Triangle triangles[];

} triBuffer;

layout(binding = 2) readonly buffer BVHBuffer {

    BVHNode nodes[];

} bvhBuffer;

layout(binding = 3) uniform CameraUBO {

    vec4 position;
    vec4 forward;
    vec4 right;
    vec4 up;

} camera;

const vec3 lightMin = vec3(0.86, 1.99, 0.2);
const vec3 lightMax = vec3( 1.24, 1.99, 0.6);

const vec3 backRoomsWall = vec3(0.86, 0.78, 0.29);
const vec3 lightColor = vec3(1.0, 0.96, 0.80);

struct Light {
    vec3 minP;
    vec3 maxP;
};

#define MAX_LIGHTS 64
Light gLights[MAX_LIGHTS];
int gLightCount = 0;



// ------------- LABYRINTH ----------

struct Room {

    vec3 min;
    vec3 max;

};

const int MAP_W = 5;
const int MAP_H = 5;


const int map[25] = int[](
    3, 1, 1, 2, 3,
    6, 4, 2, 0, 0,
    3, 0, 6, 1, 2,
    0, 0, 3, 0, 2,
    6, 1, 2, 6, 5
);

// ------------- RANDOM -------------

uint rngState;

uint pcg(uint v) {
    uint state = v * 747796405u + 2891336453u;
    uint word  = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
    return (word >> 22u) ^ word;
}

float rand() {
    rngState = pcg(rngState);
    return float(rngState) / float(0xFFFFFFFFu);
}

vec3 randomHemisphere(vec3 normal) {

    float u1 = rand();
    float u2 = rand();

    float r   = sqrt(u1);
    float phi = 2.0 * 3.14159265 * u2;

    vec3 localDir = vec3(r * cos(phi), r * sin(phi), sqrt(1.0 - u1));

    vec3 up      = abs(normal.y) < 0.9 ? vec3(0,1,0) : vec3(1,0,0);
    vec3 tangent = normalize(cross(up, normal));
    vec3 bitang  = cross(normal, tangent);

    return normalize(tangent * localDir.x + bitang * localDir.y + normal * localDir.z);

}

// ---------------- RANDOM ----------------

vec3 randomPointOnLight() {

    float u = rand();
    float v = rand();
    return vec3(

        mix(lightMin.x, lightMax.x, u),
        lightMin.y,
        mix(lightMin.z, lightMax.z, v)

    );

}

bool hitQuad(Ray ray, vec3 minP, vec3 maxP, vec3 normal, vec3 color, bool isLight, inout HitInfo closest) {
    
    // The normal is the normal coming out from the wall. For example, the floor has a plane normal going upwards, giving : vec3(0, 1, 0) (y=1)
    // And, the right wall has a normal going left, vec3(-1,0,0) (x=-1)

    float denom = dot(normal, ray.dir);

    if (abs(denom) < 0.0001) return false;

    vec3 planePoint = (minP + maxP) * 0.5;
    float planeD = dot(normal, planePoint);
    float t = (planeD - dot(normal, ray.origin)) / denom;
    
    if (t < 0.001 || t >= closest.t) return false;

    vec3 p = ray.origin + t * ray.dir;


    if (abs(normal.x) > 0.5) {
    
        if (p.y < minP.y || p.y > maxP.y) return false;
        if (p.z < minP.z || p.z > maxP.z) return false;
    
    } else if (abs(normal.y) > 0.5) {
    
        if (p.x < minP.x || p.x > maxP.x) return false;
        if (p.z < minP.z || p.z > maxP.z) return false;
    
    } else {

        if (p.x < minP.x || p.x > maxP.x) return false;
        if (p.y < minP.y || p.y > maxP.y) return false;
    
    }

    closest.t = t;
    closest.normal = denom < 0.0 ? normal : -normal;
    closest.color = color;
    closest.isLight = isLight;
    return true;

}

bool hitTriangle(Ray ray, Triangle tri, inout HitInfo closest) {
    vec3 v0 = tri.v0.xyz;
    vec3 v1 = tri.v1.xyz;
    vec3 v2 = tri.v2.xyz;

    vec3 e1 = v1 - v0;
    vec3 e2 = v2 - v0;
    vec3 h = cross(ray.dir, e2);
    float a = dot(e1, h);

    if (abs(a) < 0.0001) return false;

    float f = 1.0 / a;
    vec3 s = ray.origin - v0;
    float u = f * dot(s, h);
    if (u < 0.0 || u > 1.0) return false;

    vec3 q = cross(s, e1);
    float v = f * dot(ray.dir, q);
    if (v < 0.0 || u + v > 1.0) return false;

    float t = f * dot(e2, q);
    if (t < 0.001 || t >= closest.t) return false;

    closest.t = t;
    closest.normal = tri.normal.xyz;
    closest.color = vec3(0.8, 0.8, 0.8);
    closest.isLight = false;
    return true;
}

bool triangleLoop(Ray ray, inout HitInfo hit) {

    bool didHit = false;
   
    for (int i = 0; i < triBuffer.triangles.length(); i++) {
   
        didHit = hitTriangle(ray, triBuffer.triangles[i], hit) || didHit;
   
    }
    return didHit;

}

bool hitAABB(Ray ray, vec3 aabbMin, vec3 aabbMax, float tMax){

    vec3 invDir = 1.0 / ray.dir; // to avoid division since its more expensive than multiplication
    
    vec3 t0 = (aabbMin - ray.origin) * invDir;
    vec3 t1 = (aabbMax - ray.origin) * invDir;
    
    // from which way does it enter the box
    vec3 tMin = min(t0, t1); 
    vec3 tMax3 = max(t0, t1);
    
    // the largest tMin is the entry point, the smallest tMax is the exit point
    float tEnter = max(max(tMin.x, tMin.y), tMin.z);
    float tExit  = min(min(tMax3.x, tMax3.y), tMax3.z);

    // check if x, y and z interval are all inside the box at the same time.
    return tEnter <= tExit && tExit > 0.001 && tEnter < tMax;

}

bool hitBVH(Ray ray, inout HitInfo hit){

    bool didHit = false;
    int stack[32]; 
    int stackPtr = 0;
    stack[stackPtr++] = 0; // Root

    while(stackPtr > 0 ){

        int nodeIdx = stack[--stackPtr]; 
        BVHNode node = bvhBuffer.nodes[nodeIdx];

        if(!hitAABB(ray, node.aabbMin, node.aabbMax, hit.t)) continue;

        if(node.triangleCount > 0){

           for(int i = node.triangleStart; i < node.triangleStart + node.triangleCount; i++){
               
                didHit = hitTriangle(ray, triBuffer.triangles[i], hit) || didHit;
            
            }

        } else {
         
            stack[stackPtr++] = node.leftChild; // writes over root index. 
            stack[stackPtr++] = node.rightChild;
        
        }

    }

    return didHit;

}


bool hitCornellBox(Ray ray, inout HitInfo hit){

    bool didHit = false;

    didHit = hitQuad(ray, vec3(-1, 0,0), vec3( 1, 0, 2), vec3(0, 1,0),  backRoomsWall, false, hit) || didHit; // Floor
    didHit = hitQuad(ray, vec3(-1, 2,0), vec3( 1, 2, 2), vec3(0,-1,0),  backRoomsWall, false, hit) || didHit; // Roof
    didHit = hitQuad(ray, vec3(-1, 0,0), vec3(-1, 2, 2), vec3(1, 0,0),  backRoomsWall, false, hit) || didHit; // Left
    didHit = hitQuad(ray, vec3( 1, 0,0), vec3( 1, 2, 2), vec3(-1,0,0),  backRoomsWall, false, hit) || didHit; // Right
    didHit = hitQuad(ray, vec3(-1, 0,0), vec3( 1, 2, 2), vec3(0, 0,-1), backRoomsWall, false, hit) || didHit; // Back

    vec3 lightMinBox = vec3(-0.24, 1.99, 0.2);
    vec3 lightMaxBox = vec3(0.24, 1.99, 0.6);

    Light l;
    l.minP = lightMinBox;
    l.maxP = lightMaxBox;
    gLights[gLightCount++] = l;

    didHit = hitQuad(ray, lightMinBox, lightMaxBox, vec3(0,-1,0), lightColor, true, hit) || didHit; // Light

    didHit = hitBVH(ray, hit) || didHit;

    vec3 boxMin = vec3(-0.4, 0.0, 0.33);
    vec3 boxMax = vec3( 0.0, 0.6, 0.53);
    vec3 boxColor = vec3(0.8);

    // --------------- FURNITURE ---------------------------

    #ifdef FURNITURE
        // BOX
        didHit = hitQuad(ray, vec3(boxMin.x, boxMax.y, boxMin.z), vec3(boxMax.x, boxMax.y, boxMax.z), vec3(0,-1,0), boxColor, false, hit) || didHit;
        didHit = hitQuad(ray, vec3(boxMin.x, boxMin.y, boxMin.z), vec3(boxMax.x, boxMin.y, boxMax.z), vec3(0,1,0), boxColor, false, hit) || didHit;
        didHit = hitQuad(ray, vec3(boxMin.x, boxMin.y, boxMin.z), vec3(boxMin.x, boxMax.y, boxMax.z), vec3(1,0,0), boxColor, false, hit) || didHit;
        didHit = hitQuad(ray, vec3(boxMax.x, boxMin.y, boxMin.z), vec3(boxMax.x, boxMax.y, boxMax.z), vec3(-1,0,0), boxColor, false, hit) || didHit;
        didHit = hitQuad(ray, vec3(boxMin.x, boxMin.y, boxMax.z), vec3(boxMax.x, boxMax.y, boxMax.z), vec3(0,0,-1), boxColor, false, hit) || didHit;
        didHit = hitQuad(ray, vec3(boxMin.x, boxMin.y, boxMin.z), vec3(boxMax.x, boxMax.y, boxMin.z), vec3(0,0,1), boxColor, false, hit) || didHit;
    
    #endif

    return didHit;

}

bool hitMap(Ray ray, inout HitInfo hit){

    bool didHit = false;

    int CELL =4;
    int H = 2;

    for(int row = 0; row < MAP_W; row++){

        for(int col = 0; col < MAP_H; col++){
            vec3 o = vec3(float(col) * CELL, 0.0, float(row) * CELL);   

            Light l;
            l.minP = lightMin + o;
            l.maxP = lightMax + o;
            gLights[gLightCount++] = l;

            int type = map[row * MAP_W + col];

            if(type == 0){

                didHit = hitQuad(ray, o + vec3(0,0,0), o + vec3(CELL,0,CELL), vec3(0,1,0),  backRoomsWall, false, hit) || didHit;
                didHit = hitQuad(ray, o + vec3(0,H,0), o + vec3(CELL,H,CELL), vec3(0,-1,0), backRoomsWall, false, hit) || didHit;

            } else if(type == 1){

                didHit = hitQuad(ray, o + vec3(0,0,0), o + vec3(CELL,0,CELL), vec3(0,1,0),  backRoomsWall, false, hit) || didHit;
                didHit = hitQuad(ray, o + vec3(0,H,0), o + vec3(CELL,H,CELL), vec3(0,-1,0), backRoomsWall, false, hit) || didHit;

                didHit = hitQuad(ray, l.minP, l.maxP, vec3(0,-1,0), lightColor, true, hit) || didHit;

            }else if(type == 2){

                didHit = hitQuad(ray, o + vec3(0,0,0), o + vec3(CELL,0,CELL), vec3(0,1,0),  backRoomsWall, false, hit) || didHit;
                didHit = hitQuad(ray, o + vec3(0,H,0), o + vec3(CELL,H,CELL), vec3(0,-1,0), backRoomsWall, false, hit) || didHit;
                didHit = hitQuad(ray, o + vec3(CELL,0,0), o + vec3(CELL,H,CELL), vec3(-1,0,0), backRoomsWall, false, hit) || didHit; // Right
                didHit = hitQuad(ray, l.minP, l.maxP, vec3(0,-1,0), lightColor, true, hit) || didHit;


            } else if(type == 3){

                didHit = hitQuad(ray, o + vec3(0,0,0), o + vec3(CELL,0,CELL), vec3(0,1,0),  backRoomsWall, false, hit) || didHit;
                didHit = hitQuad(ray, o + vec3(0,H,0), o + vec3(CELL,H,CELL), vec3(0,-1,0), backRoomsWall, false, hit) || didHit;
                didHit = hitQuad(ray, o + vec3(0,0,0), o + vec3(0,H,CELL), vec3(1,0,0), backRoomsWall, false, hit) || didHit;  // Left
                didHit = hitQuad(ray, l.minP, l.maxP, vec3(0,-1,0), lightColor, true, hit) || didHit;


            } else if(type == 4){


                didHit = hitQuad(ray, o + vec3(0,0,0), o + vec3(CELL,0,CELL), vec3(0,1,0),  backRoomsWall, false, hit) || didHit;
                didHit = hitQuad(ray, o + vec3(0,H,0), o + vec3(CELL,H,CELL), vec3(0,-1,0), backRoomsWall, false, hit) || didHit;

                didHit = hitQuad(ray, l.minP, l.maxP, vec3(0,-1,0), lightColor, true, hit) || didHit;
                didHit = hitQuad(ray, o + vec3(0,0,CELL), o + vec3(CELL,H,CELL), vec3(0,0,-1), backRoomsWall, false, hit) || didHit; // Back

            } else if(type == 5){

                didHit = hitQuad(ray, o + vec3(0,0,0), o + vec3(CELL,0,CELL), vec3(0,1,0),  backRoomsWall, false, hit) || didHit;
                didHit = hitQuad(ray, o + vec3(0,H,0), o + vec3(CELL,H,CELL), vec3(0,-1,0), backRoomsWall, false, hit) || didHit;

                didHit = hitQuad(ray, o + vec3(CELL,0,0), o + vec3(CELL,H,CELL), vec3(-1,0,0), backRoomsWall, false, hit) || didHit; // Right
                didHit = hitQuad(ray, o + vec3(0,0,CELL), o + vec3(CELL,H,CELL), vec3(0,0,-1), backRoomsWall, false, hit) || didHit; // Back
                didHit = hitQuad(ray, l.minP, l.maxP, vec3(0,-1,0), lightColor, true, hit) || didHit;

            }
            else if(type == 6){

                
                didHit = hitQuad(ray, o + vec3(0,0,0), o + vec3(CELL,0,CELL), vec3(0,1,0),  backRoomsWall, false, hit) || didHit;
                didHit = hitQuad(ray, o + vec3(0,H,0), o + vec3(CELL,H,CELL), vec3(0,-1,0), backRoomsWall, false, hit) || didHit;

                didHit = hitQuad(ray, o + vec3(0,0,CELL), o + vec3(CELL,H,CELL), vec3(0,0,-1), backRoomsWall, false, hit) || didHit; // Back
                didHit = hitQuad(ray, o + vec3(0,0,0), o + vec3(0,H,CELL), vec3(1,0,0), backRoomsWall, false, hit) || didHit;  // Left
                didHit = hitQuad(ray, l.minP, l.maxP, vec3(0,-1,0), lightColor, true, hit) || didHit;

            }


        }   
    }

    return didHit;


}

bool hitScene(Ray ray, inout HitInfo hit) {

    hit.t = 1e30;
    gLightCount = 0;
    bool didHit = false;

    didHit = hitCornellBox(ray, hit);

    //didHit = hitMap(ray, hit);

    return didHit;

}

Ray generateRay(ivec2 pixel, ivec2 size) {

    vec2 uv = (vec2(pixel) + 0.5) / vec2(size) * 2.0 - 1.0;
    uv.x *= float(size.x) / float(size.y);
    uv.y = -uv.y;

    float focalLength  = pc.focalLength;
    float apertureSize = pc.apertureSize;

    vec3 focalPoint = camera.position.xyz
                    + camera.forward.xyz * focalLength
                    + uv.x * camera.right.xyz * focalLength
                    + uv.y * camera.up.xyz    * focalLength;

    float angle  = rand() * 2.0 * 3.14159265;
    float radius = sqrt(rand()) * apertureSize;
    vec2  disk   = vec2(cos(angle), sin(angle)) * radius;

    vec3 lensPoint = camera.position.xyz
                   + disk.x * camera.right.xyz
                   + disk.y * camera.up.xyz;

    Ray ray;
    if(pc.useRealLens == 1){
        ray.origin = lensPoint;
    }else{
        ray.origin = camera.position.xyz;
    }
    
    ray.dir    = normalize(focalPoint - lensPoint);
    
    return ray;

}

vec3 NEE(vec3 hitPoint, vec3 hitNormal, vec3 surfaceColor) {

    if (gLightCount == 0) return vec3(0.0);

    int lightIdx = int(rand() * float(gLightCount));
    lightIdx = clamp(lightIdx, 0, gLightCount - 1);
    Light chosenLight = gLights[lightIdx];

    float u = rand();
    float v = rand();
    vec3 lightPoint = vec3(
        mix(chosenLight.minP.x, chosenLight.maxP.x, u),
        chosenLight.minP.y,
        mix(chosenLight.minP.z, chosenLight.maxP.z, v)
    );

    vec3 lightDir = lightPoint - hitPoint;
    float lightDistanceSqr = dot(lightDir, lightDir);
    float lightDistance = sqrt(lightDistanceSqr);
    vec3 shadowDir = lightDir / lightDistance;

    vec3 lightNormal = vec3(0.0, -1.0, 0.0);
    float NdotL = max(dot(hitNormal, shadowDir), 0.0);
    float NdotL_light = max(dot(lightNormal, -shadowDir), 0.0);
    if (NdotL <= 0.0 || NdotL_light <= 0.0) return vec3(0.0);

    Ray shadowRay;
    shadowRay.origin = hitPoint + hitNormal * 0.001;
    shadowRay.dir = shadowDir;

    HitInfo shadowHit;
    if (hitScene(shadowRay, shadowHit)) {
        if (!shadowHit.isLight || abs(shadowHit.t - lightDistance) > 0.01)
            return vec3(0.0);
    } else {
        return vec3(0.0);
    }

    float lightArea = (chosenLight.maxP.x - chosenLight.minP.x)
                    * (chosenLight.maxP.z - chosenLight.minP.z);

    vec3 brdf = surfaceColor / 3.14159265;
    vec3 lightEmission = vec3(15.0);

   
    vec3 directLight = float(gLightCount) * lightEmission * brdf * NdotL * NdotL_light * lightArea / lightDistanceSqr;

    return directLight;
}

vec3 tracePath(Ray ray) {

    vec3 throughput = vec3(1.0);
    vec3 color      = vec3(0.0);

    const int MAX_BOUNCES = 4;

    for (int bounce = 0; bounce < MAX_BOUNCES; bounce++) {

        HitInfo hit;
        if (!hitScene(ray, hit)) break;


        if(pc.useNEE == 1){
            if (hit.isLight) {
                if (bounce == 0) {
                    color += throughput * vec3(15.0);
                }
                break;
            }
        }

        if(pc.useNEE == 0){
            if(hit.isLight){

                color += throughput * vec3(15.0);
                break;

            }
        }

        vec3 hitPoint = ray.origin + hit.t * ray.dir + hit.normal * 0.001;
        vec3 hitNormal = hit.normal;
        vec3 hitColor = hit.color;

        if(pc.useNEE == 1){

            color += throughput * NEE(hitPoint, hitNormal, hitColor);
        
        }

        ray.origin = hitPoint + hitNormal * 0.001;
        ray.dir    = randomHemisphere(hitNormal);

        throughput *= hitColor;

        float p = max(throughput.r, max(throughput.g, throughput.b));
        if (rand() > p) break;
        throughput /= p;
    }

    return color;

}

void main() {

    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    
    ivec2 size  = imageSize(outImage);

    rngState = uint(pixel.x) * 1973u + uint(pixel.y) * 9277u + pc.frameCount * 26699u + 1u;

    if (pixel.x >= size.x || pixel.y >= size.y) return;

    const int SAMPLES = 6;
    vec3 col = vec3(0.0);

    for (int s = 0; s < SAMPLES; s++) {

        Ray ray = generateRay(pixel, size);
        col += tracePath(ray);
    
    }

    col /= float(SAMPLES);

    vec3 oldColor    = imageLoad(outImage, pixel).rgb;
    vec3 accumulated = (oldColor * float(pc.frameCount) + col) / float(pc.frameCount + 1);

    imageStore(outImage, pixel, vec4(accumulated, 1.0));

}